name: Copy files

on: 
  push:
    branches: 
      - main
    paths:
      - 'tokens/*'

jobs:
  copy_files_to_theme_project: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
      with:
        source_folder: 'tokens'
        destination_repo: 'six7/multirepo-theme'
        destination_folder: 'tokens/core'
        user_email: 'six.jan@gmail.com'
        user_name: 'six7'
        commit_msg: 'Update core files'
