name: Copy updated OpenAPI file

# only run this workflow when the openapi file has changed on the master branch
on: 
  push:
    branches: 
      - main
    paths:
      - 'tokens/*'

jobs:
  copy_files_to_theme_project: 
    runs-on: ubuntu-latest
    steps:
    - name: Push tokens to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
      with:
        source-files: 'tokens/'
        destination-branch: 'main'
        destination-username: 'six7'
        destination-repository: 'multirepo-theme'
        destination-directory: 'tokens/core'
